// GENERATED by scripts/codegen.mjs — do not edit by hand.
// Source of truth: schemas/ch.v0.1.*.json

export type MessageContent = TextPart | CodeBlockPart | ImageRefPart | ToolUsePart | AttachmentRefPart;

/**
 * ContextHub portable conversation format, version ch.v0.1.
 */
export interface ConversationV0 {
  spec_version: "ch.v0.1";
  source: Source;
  messages: Message[];
  metadata?: Metadata;
}
export interface Source {
  platform: "claude_ai";
  conversation_id?: string;
  url?: string;
  model?: string;
  captured_at: string;
}
export interface Message {
  role: "user" | "assistant" | "system";
  content: MessageContent[];
  created_at?: string;
}
export interface TextPart {
  type: "text";
  text: string;
}
export interface CodeBlockPart {
  type: "code_block";
  language?: string;
  body: string;
}
export interface ImageRefPart {
  type: "image_ref";
  url?: string;
  storage_path?: string;
  mime_type?: string;
  alt_text?: string;
}
export interface ToolUsePart {
  type: "tool_use";
  name: string;
  input?: string;
  output?: string;
}
export interface AttachmentRefPart {
  type: "attachment_ref";
  filename: string;
  mime_type?: string;
  size_bytes?: number;
  storage_path?: string;
}
export interface Metadata {
  title?: string;
  client_version?: string;
  user_agent?: string;
}

/**
 * ContextHub structured-block format, version ch.v0.1. The authoritative shape for push summaries' structured-block layer.
 */
export interface StructuredBlockV0 {
  spec_version: "ch.v0.1";
  decisions: Decision[];
  artifacts: Artifact[];
  open_questions: OpenQuestion[];
  assumptions: string[];
  constraints: string[];
}
export interface Decision {
  title: string;
  rationale: string;
  message_refs?: number[];
}
export interface Artifact {
  kind: "schema" | "code" | "outline" | "other";
  name: string;
  body: string;
  language?: string;
}
export interface OpenQuestion {
  question: string;
  context?: string;
}
