# GENERATED by scripts/codegen_py.py — do not edit by hand.
# Source of truth: schemas/ch.v0.1.*.json
# To regenerate: `pnpm --filter @contexthub/interchange-spec run codegen:py`

from __future__ import annotations

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel
from typing import Annotated, Literal

class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform: Literal['claude_ai']
    conversation_id: str | None = None
    url: AnyUrl | None = None
    model: str | None = None
    captured_at: AwareDatetime


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str | None = None
    client_version: str | None = None
    user_agent: str | None = None


class TextPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    text: str


class CodeBlockPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['code_block']
    language: str | None = None
    body: str


class ImageRefPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['image_ref']
    url: str | None = None
    storage_path: str | None = None
    mime_type: str | None = None
    alt_text: str | None = None


class ToolUsePart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['tool_use']
    name: str
    input: str | None = None
    output: str | None = None


class AttachmentRefPart(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['attachment_ref']
    filename: str
    mime_type: str | None = None
    size_bytes: Annotated[int | None, Field(ge=0)] = None
    storage_path: str | None = None


class MessageContent(
    RootModel[TextPart | CodeBlockPart | ImageRefPart | ToolUsePart | AttachmentRefPart]
):
    root: TextPart | CodeBlockPart | ImageRefPart | ToolUsePart | AttachmentRefPart


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    role: Literal['user', 'assistant', 'system']
    content: list[MessageContent]
    created_at: AwareDatetime | None = None


class ConversationV0(BaseModel):
    """
    ContextHub portable conversation format, version ch.v0.1.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    spec_version: Literal['ch.v0.1']
    source: Source
    messages: list[Message]
    metadata: Metadata | None = None

class MessageRef(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Decision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: str
    rationale: str
    message_refs: list[MessageRef] | None = None


class Artifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['schema', 'code', 'outline', 'other']
    name: str
    body: str
    language: str | None = None


class OpenQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question: str
    context: str | None = None


class StructuredBlockV0(BaseModel):
    """
    ContextHub structured-block format, version ch.v0.1. The authoritative shape for push summaries' structured-block layer.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    spec_version: Literal['ch.v0.1']
    decisions: list[Decision]
    artifacts: list[Artifact]
    open_questions: list[OpenQuestion]
    assumptions: list[str]
    constraints: list[str]
