#!/usr/bin/env python
"""Regenerate `python/contexthub_interchange/models.py` from JSON Schemas.

Invoked by `pnpm --filter @contexthub/interchange-spec run codegen:py`.
CI drift-checks the output: if regeneration produces a different file than
what's committed, CI fails the drift job.

Strategy: datamodel-codegen runs per-schema into temp files, then the
per-module imports are merged and intermediate headers stripped so the
committed output is a single coherent file.
"""

from __future__ import annotations

import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path
from tempfile import NamedTemporaryFile

PKG_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PKG_ROOT.parent.parent
SCHEMAS = [
    PKG_ROOT / "schemas" / "ch.v0.1.conversation.json",
    PKG_ROOT / "schemas" / "ch.v0.1.structured-block.json",
]
OUT = PKG_ROOT / "python" / "contexthub_interchange" / "models.py"

BANNER = (
    "# GENERATED by scripts/codegen_py.py — do not edit by hand.\n"
    "# Source of truth: schemas/ch.v0.1.*.json\n"
    "# To regenerate: `pnpm --filter @contexthub/interchange-spec run codegen:py`\n"
)

IMPORT_FROM_RE = re.compile(r"^from\s+(\S+)\s+import\s+(.+?)\s*$")
IMPORT_BARE_RE = re.compile(r"^import\s+(.+?)\s*$")
HEADER_COMMENT_RE = re.compile(r"^#\s*(generated by datamodel-codegen|\s*filename:|\s*timestamp:)")


def _generate_one(schema: Path) -> str:
    with NamedTemporaryFile(suffix=".py", mode="r", delete=False) as tmp:
        pass
    tmp_path = Path(tmp.name)
    try:
        subprocess.run(
            [
                "datamodel-codegen",
                "--input",
                str(schema),
                "--output",
                str(tmp_path),
                "--input-file-type",
                "jsonschema",
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--target-python-version",
                "3.12",
                "--use-standard-collections",
                "--use-union-operator",
                "--use-schema-description",
                "--use-annotated",
                "--disable-timestamp",
                "--enum-field-as-literal",
                "all",
            ],
            check=True,
        )
        return tmp_path.read_text(encoding="utf-8")
    finally:
        tmp_path.unlink(missing_ok=True)


def _split(source: str) -> tuple[dict[str, set[str]], set[str], list[str]]:
    """Return (from_imports by module, bare imports, body lines)."""
    from_imports: dict[str, set[str]] = defaultdict(set)
    bare_imports: set[str] = set()
    body: list[str] = []
    for raw_line in source.splitlines():
        line = raw_line.rstrip()
        if HEADER_COMMENT_RE.match(line):
            continue
        m = IMPORT_FROM_RE.match(line)
        if m:
            module, names = m.group(1), m.group(2)
            for n in (x.strip() for x in names.split(",")):
                if n:
                    from_imports[module].add(n)
            continue
        mb = IMPORT_BARE_RE.match(line)
        if mb:
            for n in (x.strip() for x in mb.group(1).split(",")):
                if n:
                    bare_imports.add(n)
            continue
        body.append(line)
    return from_imports, bare_imports, body


def _strip_leading_blank(lines: list[str]) -> list[str]:
    while lines and not lines[0].strip():
        lines.pop(0)
    return lines


def main() -> int:
    from_imports: dict[str, set[str]] = defaultdict(set)
    bare_imports: set[str] = set()
    bodies: list[list[str]] = []
    for schema in SCHEMAS:
        src = _generate_one(schema)
        fi, bi, body = _split(src)
        for module, names in fi.items():
            from_imports[module].update(names)
        bare_imports.update(bi)
        bodies.append(_strip_leading_blank(body))

    lines: list[str] = [BANNER.rstrip(), ""]
    # __future__ must come first if present.
    if "__future__" in from_imports:
        names = sorted(from_imports.pop("__future__"))
        lines.append(f"from __future__ import {', '.join(names)}")
        lines.append("")
    for module in sorted(bare_imports):
        lines.append(f"import {module}")
    for module in sorted(from_imports):
        names = sorted(from_imports[module])
        lines.append(f"from {module} import {', '.join(names)}")
    lines.append("")

    # Bodies separated by a single blank line.
    merged_body: list[str] = []
    for body in bodies:
        if merged_body:
            # Ensure exactly one blank line between bodies.
            while merged_body and not merged_body[-1].strip():
                merged_body.pop()
            merged_body.append("")
        merged_body.extend(body)
    # Trim trailing blank lines.
    while merged_body and not merged_body[-1].strip():
        merged_body.pop()
    lines.extend(merged_body)

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
