#!/usr/bin/env node
/**
 * Regenerate packages/interchange-spec/src/models.ts from the JSON Schemas.
 * Invoked by `pnpm run codegen`. CI drift-checks the result.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const SCHEMAS = {
  conversation: resolve(PKG_ROOT, "schemas/ch.v0.1.conversation.json"),
  structuredBlock: resolve(PKG_ROOT, "schemas/ch.v0.1.structured-block.json"),
};
const OUT = resolve(PKG_ROOT, "src/models.ts");

const options = {
  additionalProperties: false,
  bannerComment: [
    "// GENERATED by scripts/codegen.mjs — do not edit by hand.",
    "// Source of truth: schemas/ch.v0.1.*.json",
  ].join("\n"),
  style: { singleQuote: false, semi: true, trailingComma: "all" },
};

const convSchema = JSON.parse(readFileSync(SCHEMAS.conversation, "utf8"));
const sbSchema = JSON.parse(readFileSync(SCHEMAS.structuredBlock, "utf8"));

const convTs = await compile(convSchema, "ConversationV0", options);
const sbTs = await compile(sbSchema, "StructuredBlockV0", { ...options, bannerComment: "" });

const combined = `${convTs}\n${sbTs}`;

writeFileSync(OUT, combined, "utf8");
console.log(`wrote ${OUT}`);
