"""ContextHub interchange format — ch.v0.1.

Pydantic models, markdown renderer, and validator CLI.
Schemas are the source of truth; models are regenerated by datamodel-code-generator.
"""

from .models import (
    Artifact,
    AttachmentRefPart,
    CodeBlockPart,
    ConversationV0,
    Decision,
    ImageRefPart,
    Message,
    Metadata,
    OpenQuestion,
    Source,
    StructuredBlockV0,
    TextPart,
    ToolUsePart,
)
from .renderer import render_structured_block

SPEC_VERSION = "ch.v0.1"

__all__ = [
    "SPEC_VERSION",
    "Artifact",
    "AttachmentRefPart",
    "CodeBlockPart",
    "ConversationV0",
    "Decision",
    "ImageRefPart",
    "Message",
    "Metadata",
    "OpenQuestion",
    "Source",
    "StructuredBlockV0",
    "TextPart",
    "ToolUsePart",
    "render_structured_block",
]
